from flask import Flask, render_template, request
from requests import get
from api import grab_url
from random import choice, randint

app = Flask(__name__)

# Uses the https://api.le-systeme-solaire.net/ solar system data API

@app.route("/", methods=["GET", "POST"])
async def index():
    if request.method == "POST":    # Index.html receives info from user and POSTS it to our flask app!

        # Here is where we can set variables used by both random and dropdown methods
        is_planet: bool = True  # useful for determining path for object image
        object_name: str = str(request.form['object_name'])  # the selected object from our site (planet name or "I'm feeling lucky")

        # If object is chosen via randomness, pick a random name!
        if object_name == "I'm feeling lucky":
            space_res = get("https://api.le-systeme-solaire.net/rest/bodies/")  # grabbing api's data to choose
            space_data = space_res.json()  # convert it into a JSON object
            num_bodies = len(space_data["bodies"])  # tells us how many bodies are in the data
            index: int = randint(0, num_bodies-1)  # pick a random index into the bodies list
            data = space_data['bodies'][index]  # picks a random body from the response
            object_name = data["englishName"]  # reassigns object_name to be our randomly generated obj
            is_planet = False  # marks our object as not a planet
        else:
            # TODO: make your api request for the object when specified by dropdown
            refined_res = get(f"https://api.le-systeme-solaire.net/rest/bodies/{object_name}")  # we can also grab data by passing a full path
            data = refined_res.json()  # convert to a JSON object
            is_planet = True  # marks our object as a planet

        # TODO: populate args to send to result.html (object_name, moons, temp, discovered_by, discovery_date, and url)
        temp: float = data["avgTemp"]
        discovered_by: str = data["discoveredBy"]
        discovery_date: str = data["discoveryDate"]
        moons: list[str] = []
        url: str = grab_url(object_name, is_planet)

        if data["moons"] != None:
            for entry in data["moons"]:
                moons.append(entry['moon'])

        # helps with error handling
        # if object_name == '':
        #     return render_template("index.html")

        # rendering result template with all of our fields generated by our API call!
        return render_template("result.html", object_name=object_name, moons=moons, temp=temp, discovered_by=discovered_by, discovery_date=discovery_date, url=url)

    # if request method != post, render original page
    return render_template('index.html')


# flask idiom
if __name__ == '__main__':
    app.run(debug=True)